=== miriamz/xml/INSAufgabe45/src/xmlDateien/fahrzeugdatenbank.dtd
<!--
DTD der Fahrzeugdatenbank
der Firma Oldsmobil
-->
<!ELEMENT fahrzeugdatenbank (fahrzeug*)>
<!ELEMENT fahrzeug (modellbezeichnung, seriennummer, farbe, produktionsdatum , anmerkung, motor,
ausstattungsliste)>
<!ELEMENT modellbezeichnung (#PCDATA)>
<!ELEMENT seriennummer (#PCDATA)>
<!ELEMENT farbe (#PCDATA)>
<!ELEMENT produktionsdatum (tag,monat,jahr)>
<!ELEMENT anmerkung (#PCDATA)>
<!ELEMENT motor (zylinderanzahl, brennstoffart,hubraum)>
<!ELEMENT ausstattungsliste (ausstattungsoption*)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT monat (#PCDATA)>
<!ELEMENT jahr (#PCDATA)>
<!ELEMENT zylinderanzahl (#PCDATA)>
<!ELEMENT brennstoffart (#PCDATA)>
<!ELEMENT hubraum (#PCDATA)>
<!ELEMENT ausstattungsoption (bezeichnung, anzahl, einzelpreis)>
<!ELEMENT bezeichnung (#PCDATA)>
<!ELEMENT anzahl (#PCDATA)>
<!ELEMENT einzelpreis (#PCDATA)>

=== miriamz/xml/INSAufgabe45/src/xmlDateien/Testwagen.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE fahrzeugdatenbank SYSTEM "fahrzeugdatenbank.dtd">
<fahrzeugdatenbank>
	<fahrzeug>
		<modellbezeichnung>Testwagen-93</modellbezeichnung>
		<seriennummer>985-5885-87</seriennummer>
		<farbe>Rot</farbe>
		<produktionsdatum>
			<tag>25</tag>
			<monat>09</monat>
			<jahr>1994</jahr>
		</produktionsdatum>
		<anmerkung>
		Dies ist ein toller schneller unglaublicher Wagen.
		</anmerkung>
		<motor>
			<zylinderanzahl>2</zylinderanzahl>
			<brennstoffart>Benzin</brennstoffart>
			<hubraum>5,7 Liter</hubraum>
		</motor>
		<ausstattungsliste>
			<ausstattungsoption>
				<bezeichnung>Heckspoiler</bezeichnung>
				<anzahl>1</anzahl>
				<einzelpreis>50</einzelpreis>
			</ausstattungsoption>
			<ausstattungsoption>
			<bezeichnung>Sportauspuff</bezeichnung>
				<anzahl>1</anzahl>
				<einzelpreis>525</einzelpreis>
			</ausstattungsoption>
		</ausstattungsliste>
	</fahrzeug>
	<fahrzeug>
		<modellbezeichnung>Testwagen-Schrott</modellbezeichnung>
		<seriennummer>985-5885-87</seriennummer>
		<farbe>Schwarz</farbe>
		<produktionsdatum>
			<tag>25</tag>
			<monat>09</monat>
			<jahr>1994</jahr>
		</produktionsdatum>
		<anmerkung>
		Dies ist unglaublicher Wagen.
		</anmerkung>
		<motor>
			<zylinderanzahl>2</zylinderanzahl>
			<brennstoffart>Benzin</brennstoffart>
			<hubraum>5,7 Liter</hubraum>
		</motor>
		<ausstattungsliste>
			<ausstattungsoption>
				<bezeichnung>Heckspoiler</bezeichnung>
				<anzahl>1</anzahl>
				<einzelpreis>50</einzelpreis>
			</ausstattungsoption>
			<ausstattungsoption>
			<bezeichnung>Sportauspuff</bezeichnung>
				<anzahl>1</anzahl>
				<einzelpreis>525</einzelpreis>
			</ausstattungsoption>
		</ausstattungsliste>
	</fahrzeug>
</fahrzeugdatenbank>
